import type { CSSProperties } from "react";
import DatabaseSchema from "./DatabaseSchema";
import { BUCKETS } from "./schema-data";

/* Database Schema & Data Layer — overview, table inventory by group, then the interactive diagram.
   Table → schema mapping is read from the JPA entities; every service shares this one database. */

const TABLE_COUNT = BUCKETS.reduce((n, b) => n + b.entities.length, 0);

const P: CSSProperties = { fontSize: "15px", lineHeight: 1.8, color: "var(--ink-70)", width: "100%" };
const M = (t: string) => <span className="mono" style={{ fontSize: "13px", color: "var(--ink)" }}>{t}</span>;

export default function DataLayer() {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 40 }}>
      <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
        <h3 className="font-light tracking-tight" style={{ fontSize: "clamp(1.3rem, 2.2vw, 1.6rem)", color: "var(--ink)" }}>
          Database Schema &amp; Data Layer
        </h3>
        <p style={P}>
          Kayana Aid keeps its data in a single Postgres database that every backend service shares. Related data is
          grouped into five schemas: the charity tenant and everything it owns ({M("kayana_business")}), donor accounts
          ({M("kayana_user")}), orders and payment transactions ({M("kayana_transaction")}), platform-wide defaults such
          as fees and tax ({M("kayana_admin")}), and an audit trail of inbound payment events ({M("kayana_audit")}).
        </p>
        <p style={P}>
          Services read and write through JPA. Schema changes are made with SQL migrations rather than generated by
          Hibernate, and read-only work is sent to a separate read-only data source. Each service maps only the tables
          it needs, so core records such as the charity itself are shared by several services at once.
        </p>
        <p style={P}>
          The diagram below draws the {TABLE_COUNT} tables in eight groups — business users, business property, donors,
          campaigns and fundraising, donations, events, the hardware shop and webhook events — together with their
          foreign keys. Names are shown without their {M("kayana_")} prefix.
        </p>
      </div>

      <DatabaseSchema />
    </div>
  );
}
